services:
  postgres:
    image: postgres:16
    container_name: earthquake-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: earthquake-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # web console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  airflow-postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data

  airflow-init:
    build: ./airflow
    user: "${AIRFLOW_UID}:0"
    restart: "no"
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Tammem --lastname Admin --role Admin --email admin@example.com"
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  airflow-webserver:
    build: ./airflow
    user: "${AIRFLOW_UID}:0"
    restart: unless-stopped
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/msi/earthquake-pipeline:/home/msi/earthquake-pipeline
      - /home/msi/.dbt:/home/msi/.dbt
    group_add:
      - "${DOCKER_GID}"
    command: webserver

  airflow-scheduler:
    build: ./airflow
    user: "${AIRFLOW_UID}:0"
    restart: unless-stopped
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/msi/earthquake-pipeline:/home/msi/earthquake-pipeline
      - /home/msi/.dbt:/home/msi/.dbt
    group_add:
      - "${DOCKER_GID}"
    command: scheduler

volumes:
  postgres_data:
  minio_data:
  airflow-postgres-data: