[project]
name = "earthquake-pipeline"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "tammem", email = "tammembenyoussef2020@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
